// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoscrollController from "./autoscroll_controller"

application.register("autoscroll", AutoscrollController)

import ComposerController from "./composer_controller"

application.register("composer", ComposerController)

import DismissableController from "./dismissable_controller"

application.register("dismissable", DismissableController)

import DrawerController from "./drawer_controller"

application.register("drawer", DrawerController)

import ThemeController from "./theme_controller"

application.register("theme", ThemeController)
