default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: [ai]
      threads: <%= Integer(ENV.fetch("AI_JOB_THREADS", "5"), 10) %>
      processes: 1
      polling_interval: 0.1
    - queues: [mailers, default]
      threads: <%= Integer(ENV.fetch("DEFAULT_JOB_THREADS", "2"), 10) %>
      processes: 1
      polling_interval: 0.1

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
